services:
    app:
        image: laravelsail/php84-composer:latest
        container_name: laravel_app
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        ports:
            - "8000:8000"
        depends_on:
            - mysql
        environment:
            - DB_HOST=mysql
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=secret

    mysql:
        image: mysql:8.0
        container_name: mysql_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
